### ISSUE TITLE
licence?

### ISSUE THREAD

**Issue by dhuppenkothen** [uwescience/HackWeek-Toolkit#1]
What should this be licenced under? Will we need different licences for different folders (e.g. if one folder has code, another has text)?

**Comment by arokem** [comment]
I think that it would be fine to license the entire repo under CC-BY and add "unless otherwise specified". If we add code, we can add a BSD license for the specific code added. What do you think about that?

**Comment by dhuppenkothen** [comment]
Sounds good. I just haven't had a lot of experience with repos that include both text (other than documentation) and code, so I figured it'd be good to get some input.

**Comment by aaarendt** [comment]
Added CC-BY
